run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - gocognit
    - goconst
    - gofmt
    - goimports
    - misspell
    - unconvert
    - noctx
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
  disable:
    - gocritic  # Too many false positives
    - unparam   # Unused parameter checks can be noisy
    - prealloc  # Pre-allocation suggestions often not worth it

linters-settings:
  gosec:
    excludes:
      - G204  # Subprocess launched with variable - needed for CLI tool
      - G304  # File path provided as taint input - needed for file operations
    severity: medium
    confidence: medium

  gocyclo:
    min-complexity: 30

  gocognit:
    min-complexity: 65

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
